# -*- coding: utf-8 -*-
"""GMC_first_py.lpynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17BWhL-nWKyng1dEb4J6gVtTQTTuCOiS6

# Welcome to the world of Python!**

##We'd write our first line of code today

# Introducing The Print Function**

`print` is a built-in function in Python. Python is case sensitive i.e Print != print
"""

print("Hello World")

print("my name is victor")

print("I'm learning about github and I am going to add my work to a repository I cloned")

